on:
  workflow_dispatch:
#   push:
#     branches: [main]
#   pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: unit tests
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up python 3.12
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
            python-version: 3.12

      - name: Setup PDM
        uses: pdm-project/setup-pdm@568ddd69406b30de1774ec0044b73ae06e716aa4 # v4

      - name: Install dependencies
        run: pdm sync -d -G test

      - name: Test with pytest
        run: |
          pdm run pytest --cov=pdm --cov-config=pyproject.toml --cov-report=xml tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a # v5
