on:
  workflow_dispatch:
#   push:
#     branches: [main]
#   pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: unit tests
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up python 3.12
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
            python-version: 3.12

      - name: Setup PDM
        uses: pdm-project/setup-pdm@568ddd69406b30de1774ec0044b73ae06e716aa4 # v4

      - name: Install dependencies
        run: pdm sync -d -G test

      - name: Test with pytest
        run: |
          pdm run pytest --cov=pdm --cov-config=pyproject.toml --cov-report=xml tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4
