name: Add issues and PRs to the Kanban board

on:
  issues:
    types:
      - opened
  pull_request:

jobs:
  add-to-project:
    name: Add issues amd prs to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/pvandervelde/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
